security:
  oauth2:
    client:
      clientId: authorization-service
      clientSecret: '{bcrypt}$2a$10$sXSYDNeCQraj7ynXxgRZmeMP7ymuuCYuMpzvMWDQzAeHAWgl8tRFi'
      scope: read,write
      autoApproveScopes: '.*'
    resource:
      id: authorization-service
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgaKixqVG0FRVdZ8gAgVp
          VCn4FCWua1IUOoQerpcAFqL+WO2/2ImSUHk2gdejdcMg15wXYQX4eO2KSA+vGleN
          tWrnF5GkSwaAHqEp5fj7wqJajuhkR9wlj0+ab2jmuLBp/c6DhN4yZL1N7trOOpJZ
          IP2HyqhkeBS08Iygc2wI+/w/wlARglZ0jyUb+oexYOhSrzedKHpFlFPsxs4I1Ana
          7z/psspZcl6G6yAzMnZxbTRbEVaqAQBDYc0NGx35GJhy2voB9rgk5IdWAehPhtAP
          RXfg2fD3YF3vbS1lziaI0/bnb/yLxcq6jQC2Rh2llLz+xSyO5JQxkv/GaVz2kMaD
          FQIDAQAB
          -----END PUBLIC KEY-----
